### ISSUE TITLE
map key ${{}} Breaks syntax highlighting after it

### ISSUE THREAD

**Issue by smhmd** [andis-sprinkis/lf-vim#2]
![image](https://user-images.githubusercontent.com/46059092/75103015-1243c080-55f5-11ea-982d-4c5b931fd841.png)
![image](https://user-images.githubusercontent.com/46059092/75103019-2be50800-55f5-11ea-96ef-fd00a694c3bc.png)

**Comment by ghost** [comment]
Agh!! I thought i tested this a long time ago to fix it. Will look into it

**Comment by ghost** [comment]
Fixed. I was struggling with this one, then realized all I forgot was one word... agh. Thanks for letting me know this was an issue, never noticed as always had these at the bottom.
