### ISSUE TITLE
The repository lacks a license

### ISSUE THREAD

**Issue by andis-sprinkis** [andis-sprinkis/lf-vim#6]
What it says in the title.

**Comment by andis-sprinkis** [comment]
The Apache License 2.0 is used for Neovim, so it should be compatible with Vim and Neovim licensing if this syntax highlighting was to be merged in those projects eventually. Correct me if I'm wrong.

EDIT: Vim license being compatible with GPLv2 or later, so I should probably go with that.

**Comment by andis-sprinkis** [comment]
To account for the currently unlicensed code:

I have received the permission from the original author of this plugin [Cameron Wright](https://github.com/camnw) to manage licensing of his code in this repo.

From Cameron's writing:
> As you mentioned in an issue, the repository doesn't have a license anyways and I have absolutely no opinions or considerations to give in regards to the usage of the code contained inside.

>Besides the README, it would seem every commit belongs to you or me. I give you my explicit permission to use my contributions in whole or in part in any way you please, so that (besides the current README) there is no question as to your permission in handling this.

**Comment by andis-sprinkis** [comment]
@BachoSeven, do you agree with you contributions to the README.md of this repository being licensed under the GPLv2?

**Comment by BachoSeven** [comment]
> @BachoSeven, do you agree with you contributions to the README.md of this repository being licensed under the GPLv2?

Yep!

**Comment by andis-sprinkis** [comment]
Great. I'll add the license then.
